[package]
name = "softwarechallenge-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
thincollections = "0.5.0"
separator = "0.3.1"
chrono = "0.4.19"

[profile.dev]
opt-level = 3
overflow-checks = false